//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.18 at 10:17:54 AM EST 
//


package net.opengis.ows._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdditionalParametersBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdditionalParametersBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}AdditionalParameter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalParametersBaseType", propOrder = {
    "additionalParameter"
})
@XmlSeeAlso({
    AdditionalParametersType.class
})
public class AdditionalParametersBaseType {

    @XmlElement(name = "AdditionalParameter", required = true)
    protected AdditionalParameter additionalParameter;

    /**
     * Gets the value of the additionalParameter property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalParameter }
     *     
     */
    public AdditionalParameter getAdditionalParameter() {
        return additionalParameter;
    }

    /**
     * Sets the value of the additionalParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalParameter }
     *     
     */
    public void setAdditionalParameter(AdditionalParameter value) {
        this.additionalParameter = value;
    }

}
